name: Pushing Docker Image to DockerHub

on:
  push:
    branches:
      - master

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}

    - name: Pull the Docker image
      run: docker pull nodejs_app

    - name: Tag the Docker image
      run: docker tag nodejs_app ${{ secrets.DOCKER_USER }}/nodejs_app:latest

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USER }}/nodejs_app:latest
